name: Update wakatime
on:
  schedule:
    - cron: "0 16 * * 0"
  # Manual triggers with workflow_dispatch
  workflow_dispatch:
jobs:
  update-waka:
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@v0.3.1
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_TITLE: true
          SHOW_TOAL: true      
